In [8]:
import pandas as pd

In [10]:
df = pd.read_excel("/Net/Groups/BSI/work_scratch/ppapastefanou/data/Fluxnet_detail/raw/psi_midday_all.xlsx")
df["date"] = pd.to_datetime(df["date"])

In [11]:
df

   sample_id       date  psi_1  psi_2      time
0    FASY_01 2023-06-13  22.20  22.20       NaN
1    FASY_02 2023-06-13  19.21  19.21       NaN
2    FASY_03 2023-06-13  17.75  17.75       NaN
3    FASY_04 2023-06-13  24.41  24.41       NaN
4    FREX_05 2023-06-13  15.61  15.61       NaN
5    FREX_06 2023-06-13  20.50  20.50       NaN
6    FREX_07 2023-06-13  12.77  12.77       NaN
7    FREX_08 2023-06-13  23.60  23.60       NaN
8    FASY_01 2023-07-17  23.94  15.10       NaN
9    FASY_02 2023-07-17   5.62   6.27       NaN
10   FASY_03 2023-07-17  14.52  14.55       NaN
11   FASY_04 2023-07-17  13.94  13.97       NaN
12   FREX_05 2023-07-17  21.72  21.15       NaN
13   FREX_06 2023-07-17  24.42  24.63       NaN
14   FREX_07 2023-07-17  19.02  21.43       NaN
15   FREX_08 2023-07-17  17.45  20.02       NaN
16   FASY_01 2023-08-09  15.36  12.10       NaN
17   FASY_02 2023-08-09  10.10  16.30       NaN
18   FASY_03 2023-08-09  15.10  18.70       NaN
19   FASY_04 2023-08-09  13.50  17.43       NaN
20   FREX_05 2023-08-09  18.40  19.50       NaN
21   FREX_06 2023-08-09  18.00  17.50       NaN
22   FREX_07 2023-08-09  19.10  19.60       NaN
23   FREX_08 2023-08-09  12.40  14.37       NaN
24   FASY_01 2023-09-18  12.01  14.72       NaN
25   FASY_02 2023-09-18  11.78  11.28       NaN
26   FASY_03 2023-09-18  12.30  14.71       NaN
27   FASY_04 2023-09-18  13.73  13.04       NaN
28   FREX_05 2023-09-18  15.18  15.23       NaN
29   FREX_06 2023-09-18  21.89  22.61       NaN
30   FREX_07 2023-09-18  16.35  17.21       NaN
31   FREX_08 2023-09-18  20.29  22.42       NaN
32   FASY_01 2024-09-23  21.70  23.31  11:40:00
33   FASY_02 2024-09-23  20.53  21.66  12:53:00
34   FASY_03 2024-09-23  23.91  23.20  12:35:00
35   FASY_04 2024-09-23  19.16  18.79  12:00:00
36   FREX_05 2024-09-23  28.28  32.80  11:53:00
37   FREX_06 2024-09-23  33.06  30.58  11:26:00
38   FREX_07 2024-09-23  30.98  31.30  11:43:00
39   FREX_08 2024-09-23  33.41  30.87  12:44:00
40   FASY_01 2024-07-09  19.00  19.00  14:45:00
41   FASY_02 2024-07-09  12.50  13.00  12:30:00
42   FASY_03 2024-07-09  14.00  15.00  12:15:00
43   FASY_04 2024-07-09  14.00  14.50  14:20:00
44   FREX_05 2024-07-09  15.00  14.00  15:10:00
45   FREX_06 2024-07-09  19.50  19.50  11:55:00
46   FREX_07 2024-07-09  18.00  16.00  13:15:00
47   FREX_08 2024-07-09  16.00  17.00  13:55:00
48   FASY_01 2024-08-13  15.20  12.40  11:19:00
49   FASY_02 2024-08-13  15.20  15.30  13:45:00
50   FASY_03 2024-08-13  13.40  15.10  11:45:00
51   FASY_04 2024-08-13  18.20  17.00  12:16:00
52   FREX_05 2024-08-13  17.02  17.50  11:07:00
53   FREX_06 2024-08-13  23.80  24.10  14:00:00
54   FREX_07 2024-08-13  24.70  24.20  13:11:00
55   FREX_08 2024-08-13  21.20  21.20  12:13:00

In [12]:
df['psi_leaf_midday_avg'] = df[['psi_1', 'psi_2']].mean(axis=1)
df['prefix'] = df['sample_id'].str.split('_').str[0]
df_clean = df[df['prefix'] == 'FASY'].groupby(['date', 'prefix'])['psi_leaf_midday_avg'].mean().reset_index()
# Convert from bar to MPa
df_clean['psi_leaf_midday_avg'] *= -0.1

df_clean['date'] = df_clean['date'].dt.normalize() + pd.Timedelta(hours=14)
df_clean = df_clean[(df_clean['date'] <= '2024-09-11')]
df_clean

                 date prefix  psi_leaf_midday_avg
0 2023-06-13 14:00:00   FASY            -2.089250
1 2023-07-17 14:00:00   FASY            -1.348875
2 2023-08-09 14:00:00   FASY            -1.482375
3 2023-09-18 14:00:00   FASY            -1.294625
4 2024-07-09 14:00:00   FASY            -1.512500
5 2024-08-13 14:00:00   FASY            -1.522500

In [14]:
df_clean.to_csv("/Net/Groups/BSI/work_scratch/ppapastefanou/data/Fluxnet_detail/eval_processed/psi_leaf_midday_2023_2024_avg.csv")